// Generated by Wrangler on Sun Mar 24 2024 17:16:39 GMT+0530 (India Standard Time)
// by running `wrangler types`

interface Env {
	OPENAI_API_KEY: string;
	REPLICACHE_LICENSE_KEY: string;
	DB: D1Database;
}
